// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB24nUnQ_tOVEweyvrg5Xwr_uuXsXFaVuo',
    appId: '1:547989226180:web:98574c3a4343035e5d7f91',
    messagingSenderId: '547989226180',
    projectId: 'chatvistaa',
    authDomain: 'chatvistaa.firebaseapp.com',
    storageBucket: 'chatvistaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCODyIJYMV8pBqHXiI15fFwVJ7HlB9z9sA',
    appId: '1:547989226180:android:e61a549ad8b2be095d7f91',
    messagingSenderId: '547989226180',
    projectId: 'chatvistaa',
    storageBucket: 'chatvistaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKnM74xgOmqlba7uXzKjBSDFPe-WBAaXs',
    appId: '1:547989226180:ios:8eecfe51a28cb72a5d7f91',
    messagingSenderId: '547989226180',
    projectId: 'chatvistaa',
    storageBucket: 'chatvistaa.appspot.com',
    iosClientId: '547989226180-o7018jkmpo5umolfvrb12khdeue07ln1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatvista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKnM74xgOmqlba7uXzKjBSDFPe-WBAaXs',
    appId: '1:547989226180:ios:6dc64084686f14025d7f91',
    messagingSenderId: '547989226180',
    projectId: 'chatvistaa',
    storageBucket: 'chatvistaa.appspot.com',
    iosClientId: '547989226180-1tjc8jpd48v4lk4vr4rk5d90om7of5qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatvista.RunnerTests',
  );
}
